export const GET_ALL_RESOURCES_SUCCESS = "GET_ALL_RESOURCES_SUCCESS";
export const GET_ALL_RESOURCES_FAILURE = "GET_ALL_RESOURCES_FAILURE";
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";
export const CLEAR_RESOURCES = "CLEAR_RESOURCES";

// AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// Counter
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

// Pokemon
export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_POKEMON_DETAILS_SUCCESS = "GET_POKEMON_DETAILS_SUCCESS";
